apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app1
  template:
    metadata:
      labels:
        app: flask-app1
    spec:
      imagePullSecrets:
      - name: ibm-cloud-secret-2  # Use the secret generated
      containers:
      - name: flask-app1
        image: icr.io/my-ibm-python-app1/flask-app1:latest  # Use your image path
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app1
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080 
